language: python
python:
  - "2.7"
  - "pypy"
install:
  - pip install --upgrade pip
  - pip install pytest
  - pip install pytest-cov
  - pip install -e .
  - pip install coveralls
script:
  - py.test unicore -s --cov ./unicore
after_success:
  - coveralls
